package com.sshakusora.shadowsandpetals.registries;

public enum CreativeTabOrder {
    NATURE_LOGS,
    NATURE_STRIPPED_LOGS,
    NATURE_WOOD,
    NATURE_STRIPPED_WOOD,
    NATURE_PLANKS,
    NATURE_POSTS,
    NATURE_STRIPPED_POSTS,
    NATURE_WOOD_POSTS,
    NATURE_STRIPPED_WOOD_POSTS,
    NATURE_SLABS,
    NATURE_STAIRS,
    NATURE_FENCES,
    NATURE_FENCE_GATES,
    NATURE_PRESSURE_PLATES,
    NATURE_BUTTONS,
    NATURE_SAPLINGS,
    NATURE_LEAVES,
    NATURE_LEAVES_SLABS,
    NATURE_LEAVES_STAIRS,
    NATURE_HEDGES,
    DEFAULT
}
